source:
  type: folder               # 使用本地图片文件夹模拟实时处理
  uri: "datasets/coco/calib_images"

engine:
  type: onnx                 # onnx|rknn
  model: "artifacts/models/best.onnx"
  input_size: [640, 640]

postprocess:
  conf_threshold: 0.25
  nms_threshold: 0.60
  max_detections: 1000

runtime:
  warmup: 5
  async: false

output:
  type: tcp                  # tcp
  tcp:
    host: "127.0.0.1"
    port: 9000

classes: "config/person_classes.txt"
