source:
  type: folder                # folder|video|rtsp|gige
  uri: "assets"              # 默认读取仓库内示例图片（assets/test.jpg）

engine:
  type: rknn                 # onnx|rknn（RK3588 上使用 rknn）
  model: "artifacts/models/best_person_aug_int8.rknn"
  input_size: [640, 640]
  use_zero_copy: false

postprocess:
  conf_threshold: 0.50
  nms_threshold: 0.50
  max_detections: 300

runtime:
  warmup: 5
  async: false

output:
  type: tcp
  tcp:
    host: "127.0.0.1"
    port: 9000

classes: "config/person_classes.txt"
