source:
  type: folder
  uri: "datasets/coco/val2017"

engine:
  type: onnx
  model: "artifacts/models/best_person_aug_416_norm.onnx"
  input_size: [416, 416]

postprocess:
  conf_threshold: 0.25
  nms_threshold: 0.60
  max_detections: 1000

runtime:
  warmup: 2
  async: false

output:
  type: tcp
  tcp:
    host: "127.0.0.1"
    port: 9000

classes: "config/person_classes.txt"
